#!/usr/bin/env python3
"""Emit cross-implementation test vectors for the vault format.

Run this from the Python client; every other implementation (starting with the
Kotlin one) must reproduce these byte for byte. Canonical JSON in particular is
where independent implementations silently diverge, and the failure mode --
"vaults written on my phone will not open on my laptop" -- looks like corruption
rather than like the serialisation bug it is.

    python3 tools/gen_test_vectors.py > kmp/shared/src/commonTest/resources/vectors.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from zkvault.crypto import CTX_AUTH, CTX_KEK, KdfParams, derive_master_key, derive_subkey
from zkvault.model import Entry, VaultContents
from zkvault.vault import (
    VaultFile,
    b64e,
    canonical,
    derive_auth_secret,
    pad_payload,
    padme,
)

# Fixed inputs so the vectors are reproducible. Never use these for real data.
PASSPHRASE = "correct-horse-battery-staple-anvil-rope"
SALT = bytes(range(16))
KDF = KdfParams(salt=SALT, ops_limit=2, mem_limit_bytes=19 * 1024 * 1024)


def main() -> None:
    master = derive_master_key(PASSPHRASE, KDF)
    kek = derive_subkey(master, CTX_KEK)
    auth = derive_subkey(master, CTX_AUTH)

    contents = VaultContents(updated_at="2026-01-01T00:00:00+00:00")
    contents.updated_at = "2026-01-01T00:00:00+00:00"
    entry = Entry(
        title="GitHub", username="user@example.com", password="hunter2",
        url="https://github.com", notes="line one\nline two \"quoted\"",
        id="0" * 32, created_at="2026-01-01T00:00:00+00:00",
        updated_at="2026-01-01T00:00:00+00:00",
    )
    contents.entries.append(entry)

    vault = VaultFile.create(PASSPHRASE, contents, kdf=KDF)

    vectors = {
        "_comment": "Generated by tools/gen_test_vectors.py. Do not edit by hand.",
        "kdf": {
            "passphrase": PASSPHRASE,
            "salt_b64": b64e(SALT),
            "ops_limit": KDF.ops_limit,
            "mem_limit_bytes": KDF.mem_limit_bytes,
            "master_key_hex": master.bytes.hex(),
            "kek_hex": kek.bytes.hex(),
            "auth_secret_hex": auth.bytes.hex(),
            "auth_secret_b64": derive_auth_secret(PASSPHRASE, KDF),
        },
        "canonical_json": [
            {"input": obj, "output": canonical(obj).decode("utf-8")}
            for obj in (
                {},
                {"b": 1, "a": 2},
                {"nested": {"z": 1, "a": {"deep": "value"}}, "list": [1, "two", {"k": "v"}]},
                {"unicode": "naïve café 日本語"},
                {"escapes": 'quote " backslash \\ newline \n tab \t'},
            )
        ],
        "padme": [{"input": n, "output": padme(n)} for n in
                  (0, 1, 100, 1024, 1025, 2000, 5000, 100000, 1048576)],
        "padding_roundtrip": {
            "plaintext_hex": b"hello world".hex(),
            "padded_len": len(pad_payload(b"hello world")),
        },
        "vault": {
            "file": json.loads(vault.to_bytes()),
            "expected_entry_titles": ["GitHub"],
            "expected_entry_password": "hunter2",
            "key_binding_aad": vault._key_binding().decode("utf-8"),
            "payload_binding_aad": vault._payload_binding().decode("utf-8"),
        },
    }
    json.dump(vectors, sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
